name: automate.yml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        exclude:
          - os: ubuntu-latest
            #python-version: ['2.7','3.6','3.7','3.8','3.10']
            python-version: ['2.7']
          #- os: macos-latest
           # python-version: ['2.7','3.6','3.7','3.8','3.10']
          #- os: macos-10.15
           # python-version: ['2.7','3.6','3.7','3.8','3.10']
    steps:
      - uses: styfle/cancel-workflow-action@3079606bd087920c96acfa9ca9f806fdd0cc3afd
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Matrix
        uses: actions/setup-python@v4.6.0
        with:
          python-version: ${{ matrix.python-version }}
          #architecture: x64
      - name: autogen.sh
        run: ./autogen.sh
      - name: make
        run: make
      - name: echo
        run: |
          if: ${{ !env.ACT }}
            echo $GITHUB_WORKSPACE
          python3 -c "import sys; print(sys.version)"

