name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [6.10, 7.5.1804, 8.3.2011]

    container: centos:${{ matrix.tag }}

    steps:
      - run: dnf -y update && dnf -y install git file
        if:  ${{ matrix.tag == '8.3.2011' }}

      - run: yum -y update && yum -y install git file
        if:  ${{ matrix.tag == '6.10' || matrix.tag == '7.5.1804' }}

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags
      - run: cd ctags && ./autogen.sh
      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
