name: Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -l -i {0}

    steps:
    - run: choco install -y cygwin
      shell: pwsh

    - run: choco install -y --source cygwin git patch file libiconv-devel
    
    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2
    
    - run: printf 'cd %s' "$(cygpath '${{ github.workspace }}')" >> ~/.bashrc

    - run: git clone https://github.com/leleliu008/ctags-test ctags
    - run: cp autogen.sh ctags
    - run: cp autogen.rc ctags
    - run: cd ctags && ./autogen.sh
    - run: cd ctags && ./configure --prefix=/usr
    - run: cd ctags && make
    - run: cd ctags && make install
    - run: file /usr/bin/ctags
    - run: /usr/bin/ctags --version
