name: Fedora

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [28, 30, 33, latest, rawhide]

    container: fedora:${{ matrix.tag }}

    steps:
      - name: install xz  if needed
        run: |
          command -v xz > /dev/null && return 0
          curl -LO https://github.com/leleliu008/xz-prebuild/releases/download/5.2.5/xz-5.2.5-glibc-linux-x86_64.tar.gz
          tar vxf xz-5.2.5-glibc-linux-x86_64.tar.gz -C /opt
          ln -sf /opt/xz-5.2.5-glibc-linux-x86_64/bin/xz /usr/bin/xz
      
      - name: install git if needed
        run: |
          command -v git > /dev/null && return 0
          curl -LO https://github.com/leleliu008/git-prebuild/releases/download/2.30.2/git-2.30.2-x86_64-linux-glibc.tar.xz
          tar xf git-2.30.2-x86_64-linux-glibc.tar.xz -C /opt
          ln -sf /opt/git-2.30.2-x86_64-linux-glibc/bin/git /usr/bin/git
      
      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags
      - run: cd ctags && ./autogen.sh
      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: /usr/bin/ctags --version
