name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      matrix:
        version: [11, 12]
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/freebsd${{ matrix.version }}
        run: |
          run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
          }
          run pkg install -y git
          run git clone https://github.com/universal-ctags/ctags
          run cp autogen.sh ctags
          run cp autogen.rc ctags
          run cd ctags
          run ./autogen.sh
          run ./configure --prefix=/usr
          run make
          run make install
          run file /usr/bin/ctags
          run /usr/bin/ctags --version
