name: Gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: gentoo/stage3-amd64-nomultilib

    steps:
      - run: install -d /var/db/repos/gentoo
      - run: emerge git file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags
      - run: cd ctags && ./autogen.sh
      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
