name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        # os: [macos-11.0, macos-10.15]
        version: [10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp autogen.sh ctags
    - run: cp autogen.rc ctags
    - run: cd ctags && ./autogen.sh
    - run: cd ctags && ./configure --prefix=/usr
    - run: cd ctags && make
    - run: cd ctags && file ./ctags
    - run: cd ctags && ./ctags --version
