name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [11, 10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags

      - run: ./autogen.sh --help
      - run: ./autogen.sh -h
      - run: ./autogen.sh -V
      - run: ./autogen.sh --version
      - run: ./autogen.sh env
      - run: ./autogen.sh integrate zsh
      - run: ./autogen.sh upgrade

      - run: cd ctags && ./autogen.sh configure

      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && file ./ctags
      - run: cd ctags && ./ctags --version
