---
name: Makefile CI

on:
  push:
    branches: [ "master", "main" , "**" ]
  pull_request:
    branches: [ "master", "main" , "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: autogen.sh
      run: |
          sudo apt-get install autoconf
          ./autogen.sh configure

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
