name: Manjaro Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: jonathonf/manjaro

    steps:
      - run: |
          # https://www.reddit.com/r/linuxquestions/comments/i83xrp/arch_upgrade_keyring_issue
          pacman -Syyuu --noconfirm || {
            rm -rf /etc/pacman.d/gnupg/
            rm -rf /root/.gnupg/
            gpg --refresh-keys
            pacman-key --init && pacman-key --populate
            pacman-key --refresh-keys
          }
      - run: pacman -S --noconfirm git file sed

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags
      - run: cd ctags && ./autogen.sh
      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
