name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/openbsd6
        run: |
          export AUTOCONF_VERSION=2.69
          export AUTOMAKE_VERSION=1.16
              
          export CFLAGS='-I/usr/local/include -L/usr/local/lib'
              
          if [ ! -f /usr/local/lib/libiconv.so ] ; then
            sudo ln -s /usr/local/lib/libiconv.so.* /usr/local/lib/libiconv.so
          fi
          
          run sudo pkg_add git
          run git clone https://github.com/leleliu008/ctags-test ctags
          run cp autogen.sh ctags
          run cp autogen.rc ctags
          run cd ctags
          run ./autogen.sh
          run ./configure --prefix=/usr
          run make
          run sudo make install
          run file /usr/bin/ctags
          run ctags --version
