name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [16.04, 18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2

    - run: git clone https://github.com/leleliu008/ctags-test ctags
    - run: cp autogen.sh ctags
    - run: cp autogen.rc ctags
    - run: cd ctags && ./autogen.sh
    - run: cd ctags && ./configure --prefix=/usr
    - run: cd ctags && make
    - run: cd ctags && sudo make install
    - run: file /usr/bin/ctags
    - run: /usr/bin/ctags --version
